export const FIREBASE_API_KEY = 'AIzaSyCMAZibuhsSN6JoCa7PrgFIUDtaFVxiqW8'
export const FIREBASE_AUTH_DOMAIN = 'icpc2ua.firebaseapp.com'
export const FIREBASE_DATABASE_URL = 'https://icpc2ua.firebaseio.com'
export const FIREBASE_PROJECT_ID = 'icpc2ua'
export const FIREBASE_STORAGE_BUCKET = 'icpc2ua.appspot.com'
export const FIREBASE_MESSAGING_SENDER_ID = '530839578265'
export const FACEBOOK_APP_ID = '198939570842852'
